### Cleaning session for messy data

In [3]:
!pip install fg-data-profiling --quiet

In [14]:
import pandas as pd
import numpy as np
import data_profiling
from data_profiling import ProfileReport

In [42]:
df =  pd.read_csv('dataset\iowa_liquor_sales_2025_1262_rows_part_0001.csv')
# df

<>:1: SyntaxWarning: invalid escape sequence '\i'
<>:1: SyntaxWarning: invalid escape sequence '\i'
C:\Users\Cetaking\AppData\Local\Temp\ipykernel_35648\3201009649.py:1: SyntaxWarning: invalid escape sequence '\i'
  df =  pd.read_csv('dataset\iowa_liquor_sales_2025_1262_rows_part_0001.csv')

In [22]:
profile = ProfileReport(df, title="profiling Report", explorative=True)
# profile.to_file('report.html')
# profile.to_notebook_iframe()
# profile.to_widgets()
profile.to_file("report.json")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 17/17 [00:00<00:00, 22.75it/s]

Render JSON:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [43]:
df.shape  # data shapes

(580883, 23)

In [44]:
df.dtypes #data types

invoice_id              object
ordered_on              object
store_no                 int64
store_name              object
store_address           object
store_city              object
store_zip_code         float64
county_fips_code       float64
county_name             object
category_code            int64
category_name           object
vendor_number            int64
vendor_name             object
item_no                  int64
im_desc                 object
pack                     int64
bottle_volume_ml         int64
state_bottle_cost      float64
state_bottle_retail    float64
sales_bottles            int64
sales_dollars          float64
sales_liters           float64
sales_gallons          float64
dtype: object

In [45]:
df.isnull().sum() # data missing values

invoice_id                  0
ordered_on                  0
store_no                    0
store_name                  0
store_address             208
store_city                208
store_zip_code            208
county_fips_code          208
county_name               208
category_code               0
category_name               0
vendor_number               0
vendor_name                 0
item_no                     0
im_desc                     0
pack                        0
bottle_volume_ml            0
state_bottle_cost      580883
state_bottle_retail    580883
sales_bottles               0
sales_dollars               0
sales_liters                0
sales_gallons               0
dtype: int64

In [46]:
# transform column names, removing space 
df.columns = (
    df.columns
    .str.replace(' ', '_')
    .str.lower()
    .str.strip()
)

In [ ]:
#if i want to rename any colum label based on my requirement
df = df.rename(
    columns={
        "pack":"packs",
        "item_no":"items_number"
    }
)
df.head(0)

Empty DataFrame
Columns: [invoice_id, ordered_on, store_no, store_name, store_address, store_city, store_zip_code, county_fips_code, county_name, category_code, category_name, vendor_number, vendor_name, items_number, im_desc, packs, bottle_volume_ml, state_bottle_cost, state_bottle_retail, sales_bottles, sales_dollars, sales_liters, sales_gallons]
Index: []

In [62]:
#review the transform column name 
df.head(0)

Empty DataFrame
Columns: [invoice_id, ordered_on, store_no, store_name, store_address, store_city, store_zip_code, county_fips_code, county_name, category_code, category_name, vendor_number, vendor_name, item_no, im_desc, pack, bottle_volume_ml, state_bottle_cost, state_bottle_retail, sales_bottles, sales_dollars, sales_liters, sales_gallons]
Index: []

In [ ]:
#in case there's missing valuse in dataset how to count the percentage
# of the missing values
missing_value =  df.isnull().mean()*100
print(missing_value[missing_value>0].sort_values(ascending=False))
# this actually let us know if as data scientist our data pipeline is being good

state_bottle_retail    100.000000
state_bottle_cost      100.000000
store_address            0.035808
store_zip_code           0.035808
store_city               0.035808
county_name              0.035808
county_fips_code         0.035808
dtype: float64

In [49]:
#counting how many duplicate are in a dataset
numb_dup  = df.duplicated().sum()
numb_dup

np.int64(0)

In [51]:
#if theres was duplicate what to do next

# first this code help you see the duplicated values by column 
df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head()

# drop all duplicate value and get the new dataset
df = df.drop_duplicates()

#chech the shape again
df.shape

(580883, 23)

In [61]:
print(df.head(0))
print(df.dtypes)

Empty DataFrame
Columns: [invoice_id, ordered_on, store_no, store_name, store_address, store_city, store_zip_code, county_fips_code, county_name, category_code, category_name, vendor_number, vendor_name, item_no, im_desc, pack, bottle_volume_ml, state_bottle_cost, state_bottle_retail, sales_bottles, sales_dollars, sales_liters, sales_gallons]
Index: []
invoice_id              object
ordered_on              object
store_no                 int64
store_name              object
store_address           object
store_city              object
store_zip_code         float64
county_fips_code       float64
county_name             object
category_code            int64
category_name           object
vendor_number            int64
vendor_name             object
item_no                  int64
im_desc                 object
pack                     int64
bottle_volume_ml         int64
state_bottle_cost      float64
state_bottle_retail    float64
sales_bottles            int64
sales_dollars          float64
sales_liters           float64
sales_gallons          float64
dtype: object

In [64]:
# how to convert numerical and categorical data

#create a copy of your dataset
df = df.copy()

#numeric value in dataset let say there is a missing value 
# total amont column
for column in ['sales_bottles']:
    df[column] = df[column].fillna(df[column].median())
    

# for categorical values:
# let say there's a missing value in columns, we'll fill them by "unknown"
categorical_cols = ['state_bottle_cost', 'state_bottle_retail', 'store_address','store_city']
df[categorical_cols] = df[categorical_cols].fillna('Unknown')

In [65]:
# just to ckeck if the missing value actually was replaced
print(df.isnull().sum()[df.isnull().sum()>0])

store_zip_code      208
county_fips_code    208
county_name         208
dtype: int64

In [68]:
df.head(5)

        invoice_id  ordered_on  ...  sales_liters sales_gallons
0  INV-78192100069  2025-01-01  ...          2.25          0.59
1  INV-78192100072  2025-01-01  ...          9.00          2.37
2  INV-78192100070  2025-01-01  ...          2.25          0.59
3  INV-78192100071  2025-01-01  ...          1.50          0.39
4  INV-78192100061  2025-01-01  ...          9.00          2.37

[5 rows x 23 columns]

In [80]:
#how to map somes name in data to specifique name to
# standardizing all the categorical data to meet our requirement

for column in ['store_address','store_city']:
    df[column] = df[column].str.strip().str.upper()

store_city_map = {
    "BOONE":"Bovane City"
}
store_address_map = {
    "1111 8TH ST":"1111 8TH STREET"
}
df['store_city'] = df['store_city'].map(store_city_map).fillna(df['store_city'])
df['store_address']=df['store_address'].map(store_address_map).fillna(df['store_address'])

In [81]:
df.head(5)

        invoice_id  ordered_on  ...  sales_liters sales_gallons
0  INV-78192100069  2025-01-01  ...          2.25          0.59
1  INV-78192100072  2025-01-01  ...          9.00          2.37
2  INV-78192100070  2025-01-01  ...          2.25          0.59
3  INV-78192100071  2025-01-01  ...          1.50          0.39
4  INV-78192100061  2025-01-01  ...          9.00          2.37

[5 rows x 23 columns]

In [84]:
#how to perform chain operation 
#this help remove some sign from data to transform them for calculation

#let say if sale_dollars colum has a dollars sign or currency sign

df['sales_dollars'] = (
    df['sales_dollars']
    .astype(str)
    .str.replace(r'[$@%!,]','',regex=True)
    .str.strip()
)
df['sales_dollars'] = pd.to_numeric(df['sales_dollars'], errors='coerce')

In [86]:
df.head(4)

        invoice_id  ordered_on  ...  sales_liters sales_gallons
0  INV-78192100069  2025-01-01  ...          2.25          0.59
1  INV-78192100072  2025-01-01  ...          9.00          2.37
2  INV-78192100070  2025-01-01  ...          2.25          0.59
3  INV-78192100071  2025-01-01  ...          1.50          0.39

[4 rows x 23 columns]

In [ ]:
#how to handle mix boolean values
# let create a dictionnary calls boolean map

bool_map = {
    "Yes": True, "yes":True, "Y":True, "y":True,
    "TRUE":True, "True":True, "true":True, "1":True, 
    1:True, True:True,
    "NO":False, "no":False, "No":False, "N":False,
    "n":False, 'False':False, "false":False, "FALSE":False,
    0:False, "0":False, False:False
}
df['sales_bottles'] = df['sales_bottles'].map(bool_map).fillna(False)

In [88]:
#how to fix date in the same format 
df['ordered_on'] = pd.to_datetime(df['ordered_on'], dayfirst=False, errors='coerce')
failed = df['ordered_on'].isnull().sum()

In [89]:
#how to extract some date attrubute
df['ordered_year'] = df['ordered_on'].dt.year
df['ordered_month'] = df['ordered_on'].dt.month
df['ordered_day_of_week'] = df['ordered_on'].dt.day_name()

print(df[['ordered_on','ordered_year', 'ordered_month','ordered_day_of_week']].head())

  ordered_on  ordered_year  ordered_month ordered_day_of_week
0 2025-01-01          2025              1           Wednesday
1 2025-01-01          2025              1           Wednesday
2 2025-01-01          2025              1           Wednesday
3 2025-01-01          2025              1           Wednesday
4 2025-01-01          2025              1           Wednesday